### ISSUE TITLE
Use latest VST3 SDK

### ISSUE THREAD

**Issue by jo12bar** [jo12bar/bluesend#1]
I'm having trouble getting a working version of the latest VST3 SDK (version 3.6.9) working. This is why the README mentions using version 3.6.5 - this was the only version I could get working. https://github.com/olilarkin/wdl-ol/commit/e25910935ddea002ab368c03c1a2dfb9766ad60b attempted to get 3.6.9 working, but when using this with the only download for this version I could find I end up with multiple compiler and linker errors - it seems that Steinberg moved around a lot of files, and only incremented the PATCH version number! Any guidance at all would be appreciated. I'll revisit this once I get the time.

**Comment by olilarkin** [comment]
give me a sec and I will update master branch for vst 3.6.9

**Comment by jo12bar** [comment]
Sweet, thanks!

**Comment by jo12bar** [comment]
HAHA! IT WORKED! Thanks, @olilarkin!
